version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://short_url_3pps_user:qJVaAJXo0DhkBvz5KTakzT4szemEfcEr@postgres:5432/short_url_3pps
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=pMRwwlGnPBvFWGHTc-7ulJ9odt4yXd3AysAQbj1AJnY=
    expose:
      - "8000"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit
    restart: always
    depends_on:
      - fastapi
    # Если внутри streamlit используется API_URL, можно задать:
    environment:
      - API_URL=/api
    expose:
      - "8502"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
      - streamlit

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: short_url_3pps_user
      POSTGRES_PASSWORD: qJVaAJXo0DhkBvz5KTakzT4szemEfcEr
      POSTGRES_DB: short_url_3pps
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
