"""Add cascade deletion to LinkVisit and relationship in Link

Revision ID: 0aa760c96c46
Revises: 5d564618ecb8
Create Date: 2025-03-23 17:22:04.247481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa760c96c46'
down_revision: Union[str, None] = '5d564618ecb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
