"""Add auto_renew to Link

Revision ID: 12d08b462ecb
Revises: e2d94b518563
Create Date: 2025-03-20 19:55:57.115379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d08b462ecb'
down_revision: Union[str, None] = 'e2d94b518563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('short_code', sa.String(length=50), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_archive_id'), 'link_archive', ['id'], unique=False)
    op.add_column('links', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('links', 'auto_renew')
    op.drop_index(op.f('ix_link_archive_id'), table_name='link_archive')
    op.drop_table('link_archive')
    # ### end Alembic commands ###
